### ISSUE TITLE
Bug: nfs nos 

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#375] opened 2023-10-20 16:27 UTC
Issue opened by **btndX**

nos disappears after using it once

**Comment by naouh** [comment] 2023-12-12 21:28
Can't reproduce give us steps to reproduce so we can fix :)

**Comment by naouh** [comment] 2024-01-26 12:33
should be fixed

**Closed as completed by naouh** 2024-01-26 12:33 UTC
Labels: bug, implemented
